spring.application.name=kursywalut
nbp.api.rate.url=https://api.nbp.pl/api/exchangerates/rates/A
nbp.api.table.url=https://api.nbp.pl/api/exchangerates/tables/A
nbp.api.gold.url=https://api.nbp.pl/api/cenyzlota
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
logging.level.org.springframework.security=DEBUG
server.port=${PORT:8080}
server.forward-headers-strategy=framework
cors.allowed-origin-patterns=${CORS_ALLOWED_ORIGIN_PATTERNS:${CORS_ALLOWED_ORIGINS:http://localhost:*,http://127.0.0.1:*,https://kursywalut-seven.vercel.app}}
app.nbp.currency.history.min-date=2002-01-02
app.nbp.currency.history.max-days=93 
app.nbp.gold.history.min-date=2013-01-02
app.nbp.gold.history.max-days=93
app.nbp.gold.max-top-count=93
jwt.secret=Z29sZGVuLWtleS1mb3Itand0LXRva2VuLWdlbmVyYXRpb24xMjM0NTY3OA==
