spring.application.name=kursywalut
nbp.api.rate.url=https://api.nbp.pl/api/exchangerates/rates/A
nbp.api.table.url=https://api.nbp.pl/api/exchangerates/tables/A
nbp.api.gold.url=https://api.nbp.pl/api/cenyzlota

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
logging.level.org.springframework.security=DEBUG

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,https://kursywalut-seven.vercel.app}
server.port=${PORT:8080}
